set nocompatible
syntax on
filetype plugin indent on

set encoding=utf-8
set number
set ruler
set showcmd
set laststatus=2
set wildmenu
set scrolloff=5
set backspace=indent,eol,start

set expandtab
set shiftwidth=2
set tabstop=2
set softtabstop=2
set autoindent

set incsearch
set hlsearch
set ignorecase
set smartcase

set mouse=a
set clipboard=unnamedplus
set nobackup
set noswapfile
set undofile
set undodir=~/.vim/undo//
silent! call mkdir(expand('~/.vim/undo'), 'p')
